apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  APP_PORT: "8080"
  FRONTEND_URL: http://reactsvc.default.svc.cluster.local
  FRONTEND_PORT: "80"
  DB_HOST: app-mysql.default.svc.cluster.local
  DB_USERNAME: root

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
stringData:
  SESSION_SECRET: 3903Hfjeofjiweojf0239jf03jf2f02fjmklj0ij023fij02j
  DB_PASSWORD: rahasia

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-express
  labels:
    name: backend-express
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend-express
  template:
    metadata:
      name: backend-express
      labels:
        name: backend-express
    spec:
      containers:
        - name: backend-express
          image: giservintz/be-inventory-express:1.0.0-test
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-secret

---

apiVersion: v1
kind: Service
metadata:
  name: expresssvc
spec:
  type: NodePort
  selector:
    name: backend-express
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31222

