apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  APP_PORT: "8080"
  FRONTEND_URL: http://34.145.100.26
  FRONTEND_PORT: "80"
  DB_HOST: app-mysql.default.svc.cluster.local
  DB_USERNAME: root

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
stringData:
  SESSION_SECRET: 3903Hfjeofjiweojf0239jf03jf2f02fjmklj0ij023fij02j
  DB_PASSWORD: rahasia

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-express
  labels:
    name: backend-express
spec:
  replicas: 3
  selector:
    matchLabels:
      name: backend-express
  template:
    metadata:
      name: backend-express
      labels:
        name: backend-express
    spec:
      containers:
        - name: backend-express
          image: giservintz/be-inventory-express:1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-secret

---

apiVersion: v1
kind: Service
metadata:
  name: expresssvc
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  type: LoadBalancer
  selector:
    name: backend-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31222

